CanterburyTales/courses/urls.py
from django.urls import path

from CanterburyTales.courses import views

app_name = 'courses'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    # ALL POSSIBLE INDEX URLS
    path('search/audience/<str:audience>/<int:audience_exact>/tags/<str:tags>/<int:tags_exact>/', views.IndexView.as_view(),
         name='index_full_search'),
    path('search/audience/<str:audience>/<int:audience_exact>/tags/<str:tags>/', views.IndexView.as_view(),
         name='index_search_1'),
    path('search/audience/<str:audience>/tags/<str:tags>/<int:tags_exact>/', views.IndexView.as_view(),
         name='index_full_search_2'),
    path('search/audience/<str:audience>/tags/<str:tags>/', views.IndexView.as_view(), name='index_full_search_3'),
    path('search/audience/<str:audience>/<int:audience_exact>/', views.IndexView.as_view(), name='index_audience_search'),
    path('search/audience/<str:audience>/', views.IndexView.as_view(), name='index_audience_search'),
    path('search/tags/<str:tags>/<int:tags_exact>/', views.IndexView.as_view(), name='index_tag_search'),
    path('search/tags/<str:tags>/', views.IndexView.as_view(), name='index_tag_search'),


    # handle other urls
    path('courses/create/', views.CourseCreate.as_view(), name='create'),
    path('courses/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('courses/<int:pk>/edit', views.CourseUpdate.as_view(), name='edit'),
    path('courses/upvote/<int:pk>/', views.course_upvote, name='upvote'),
    path('courses/addDownload/<int:pk>/', views.course_add_download, name='add_download'),
    path('courses/<int:pk>/delete/', views.course_delete, name='delete'),
    path('courses/<int:c_id>/newFile/', views.add_file, name='add_file'),
    path('courses/<int:c_id>/deleteFile/<int:f_id>/', views.delete_file, name='delete_file'),

]

CanterburyTales/profiles/urls.py
# profile/urls.py
from django.urls import path

from CanterburyTales.profiles import views

app_name = 'profiles'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('<slug:slug>/', views.DetailView.as_view(), name='detail')
]

CanterburyTales/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('django.contrib.auth.urls')),
    path('', include('CanterburyTales.courses.urls')),
    path('profiles/', include('CanterburyTales.profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CanterburyTales/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError


def content_file_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "avatar.%s" % ext
    return filename


def file_size(value): # add this to some file where you can import it from
    limit = 2 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 2 MiB.')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=True, null=True)
    org_name = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    about = models.TextField(null=True)
    pic = models.ImageField(null=True, blank=True,
                            upload_to='avatars/', validators=[file_size])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.user.username


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

CanterburyTales/courses/forms.py
from django import forms
from django_select2.forms import ModelSelect2TagWidget, Select2TagWidget, Select2MultipleWidget
from CanterburyTales.courses.models import Course, Tag, Profile, CourseFile
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class CourseForm(forms.ModelForm):
    # pseudo_tags = forms.MultipleChoiceField()

    class Meta:
        model = Course
        fields = [
            'title',
            'year_written',
            'tags',
            'audience',
            'count',
            'duration',
            'description',
        ]
        widgets = {
            # 'course_files': forms.FileInput(attrs={'multiple': True})
        }
        labels = {
            'duration': 'Lesson Duration',
            'count': 'Number of lessons',
            'tags': 'Tags'

        }

    course_files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    def __init__(self, *args, **kwargs):
        course = kwargs.pop('course', '')
        super(CourseForm, self).__init__(*args, **kwargs)
        self.base_fields['tags'] = forms.ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('title'),
                                                                  widget=TagsCustomWidget(
                                                                      attrs={"data-token-separators": '[","]'}))


class TagsCustomWidget(Select2TagWidget):
    queryset = Tag.objects.all()

    @property
    def empty_label(self):
        return 'Type in tags'

    def value_from_datadict(self, data, files, name):
        '''Create objects for given non-pimary-key values. Return list of all names as name is the to_field_name.'''
        values = set(super().value_from_datadict(data, files, name))
        # This may only work for Tag, if Tag has title field.
        # You need to implement this method yourself, to ensure proper object creation.
        ids = []
        for val in values:
            if val.isdigit():
                ids.append(val)
            else:
                ids.append(Tag.objects.create(title=val.title()).id)
        return ids


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['title', 'description']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'org_name',
            'city',
            'state',
            'title',
            'about',
            'pic'
        ]


class FilterForm(forms.Form):
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('title'),
                                          widget=Select2MultipleWidget)
    tags_exact = forms.BooleanField(label='Exact Match',
                                    help_text='Search will return courses with any selected tags (an "or" condition). '
                                              'Exact match will return courses containing all selected tags (an "and" '
                                              'condition).')
    audience_0 = forms.IntegerField()
    audience_1 = forms.IntegerField()
    audience_exact = forms.BooleanField(label='Strict Match',
                                        help_text='Search will return courses with an audience that falls within the '
                                              'selected range. Strict match will return courses with an exact audience '
                                              'match.')

CanterburyTales/profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from .models import Profile
from django.conf import settings
from django.core.exceptions import ValidationError


def file_size(value): # add this to some file where you can import it from
    limit = 2 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 2 MiB.')


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email',)

        labels = {
            'password': "Last 4 digits of a phone number. Or any other passcode or passphrase you like",
            'password2': "Same 4 digits",
            'email': "Email"

        }
        help_texts = {
            'password1': "Your phone? Your church's phone? We will never ask for any sensitive data. So don't stress about remembering a difficult password.",
            'password2': "In case you mistyped it the first time.",
            'email': "So you can receive email notifications or others can contact you."
        }


class ProfileForm(forms.ModelForm):
    org_name = forms.CharField(max_length=100, label='Your church or organization', help_text='Church/Org')
    title = forms.CharField(max_length=50, help_text="Are you a Sunday School teacher? Youth leader? Rector?",
                            label="What's your role?")
    city = forms.CharField(max_length=50, label='City',
                           help_text="So people know a little bit about where you are from.")
    state = forms.CharField(max_length=50, label='State', help_text='State')
    about = forms.CharField(
        max_length=1000,
        label='What else should we know about you?',
        help_text='I am passionate about...',
        widget=forms.Textarea
    )
    pic = forms.FileField(label='Profile Picture', help_text='Must be less than 2Mb')

    class Meta:
        model = Profile
        fields = ('org_name', 'title', 'city', 'state', 'about', 'pic')

CanterburyTales/courses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from django import forms
from .forms import CourseForm, FilterForm
import datetime
from .models import Course, Profile, User, Tag, CourseFile, Audience
import zipfile
import os
from django.db.models import Count
from psycopg2.extras import Range, NumericRange
from django.contrib.postgres.fields import IntegerRangeField
from django.db import models
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect


class IndexView(generic.TemplateView):
    # template_name = 'courses/index.html'

    def get_template_names(self):
        if self.request.is_ajax():
            return 'courses/course_list.html'
        return 'courses/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_params'] = {
            'audience': parse_audience_params(self.kwargs.get('audience', '0,65')),
            'audience_exact': bool(self.kwargs.get('audience_exact', 0)),
            'tags': parse_tag_params(self.kwargs.get('tags', '')),
            'tags_exact': bool(self.kwargs.get('tags_exact', 0)),
        }
        context['courses'] = self.get_queryset(context['search_params'])
        context['form'] = FilterForm(initial={
            'audience_0': context['search_params']['audience'][0],
            'audience_1': context['search_params']['audience'][1],
            'audience_exact': context['search_params']['audience_exact'],
            'tags': context['search_params']['tags'],
            'tags_exact': context['search_params']['tags_exact'],
        }
        )
        return context

    def get_queryset(self, params):
        queryset = filter_audience(params['audience'], params['audience_exact'])
        queryset = filter_tags(queryset, params['tags'], params['tags_exact'])

        queryset = queryset.annotate(num_upvotes=Count('upvotes')) \
            .order_by('-num_upvotes', '-views')
        return queryset


class DetailView(generic.DetailView):
    model = Course
    template_name = 'courses/detail.html'
    fields = [
        'title',
        'year_written',
        'tags',
        'audience',
        'lesson_length',
        'description',
    ]

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        obj = self.get_object()
        obj.add_view()
        return context


class CourseCreate(LoginRequiredMixin, FormView):
    template_name = 'courses/course_form.html'
    form_class = CourseForm
    success_url = '/'
    login_url = 'login'

    def form_valid(self, form):
        course = form.save(commit=False)
        course.author = Profile.objects.all().first()
        course.posted = datetime.date.today()
        course.save()
        form.save_m2m()
        for f in form.files.getlist('course_files'):
            CourseFile.objects.create(file=f, course=course)

        return super().form_valid(form)


class CourseUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'courses/course_form.html'
    form_class = CourseForm
    model = Course
    login_url = 'login'


def course_delete(request, pk):
    course = Course.objects.get(pk=pk)
    if request.user == course.author.user:
        course.delete()
    return redirect("courses:index")


def course_upvote(request, pk):
    course = Course.objects.get(pk=pk)
    profile = request.user.profile
    course.upvotes.add(request.user.profile)
    course.save()
    return redirect('courses:index')


def course_add_download(request, pk):
    a = 1


def add_file(request, c_id):
    course = Course.objects.get(pk=c_id)
    if course.author.user == request.user:
        for file in request.FILES.getlist('course_files'):
            CourseFile.objects.create(file=file, course=course)
    return redirect('courses:detail', c_id)


def delete_file(request, course, file):
    file = CourseFile.objects.get(pk=file)
    if course == file.course.id:
        file.delete()
    return redirect('courses:detail', course)


def parse_audience_params(string):
    audience_defs = Audience().get_definitions().keys()
    a_range = string.split('-')

    if not len(a_range) == 2:
        return [0, 65]
    elif not (a_range[0].isdigit() & a_range[1].isdigit()):
        return [0, 65]
    else:
        temp_list = []
        for i in a_range:
            val = int(i)
            if val not in audience_defs:
                temp_i = 0
                for age in audience_defs:
                    if age <= val:
                        temp_i = age
                    else:
                        break
                temp_list.append(temp_i)
            else:
                temp_list.append(val)
        a_range = temp_list
    return a_range


def filter_audience(audience, match_type):
    if match_type:
        return Course.objects.filter(audience__startswith=audience[0]).filter(audience__endswith=audience[1])
    else:
        return Course.objects.filter(audience__overlap=NumericRange(audience[0], audience[1]))


def parse_tag_params(string):
    tags = []
    if string == '' or string == 'all':
        return ''

    for tag in string.split('&'):
        if tag.isdigit():
            tags.append(tag)
            tags_set = Tag.objects.filter(id__in=tags)
        else:
            tags.append(tag.title())
            tags_set = Tag.objects.filter(title__in=tags)

    return tags_set.values_list('id', flat=True)


def filter_tags(queryset, tags, match_type):
    if tags == '':
        return queryset
    if match_type:
        for tag in tags:
            queryset = queryset.filter(tags=tag)
        return queryset
    else:
        return queryset.filter(tags__in=tags)

CanterburyTales/profiles/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import SignUpForm, ProfileForm
from django.views import generic
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404


def signup(request):
    if request.method == 'POST':
        user_form = SignUpForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.refresh_from_db()
            profile_form = ProfileForm(request.POST, instance=user.profile)
            profile_form.full_clean()
            profile_form.save()
            username = user_form.cleaned_data.get('username')
            raw_password = user_form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('courses:index')
    else:
        user_form = SignUpForm()
        profile_form = ProfileForm()
    return render(request, 'profile/signup.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = User
    template_name = 'profile/detail.html'
    slug_field = 'username'
    login_url = 'login'

CanterburyTales/templates/base.html
{# HTML5 declaration #}
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One|Noto+Sans&display=swap" rel="stylesheet">

    {# Load the tag library #}
    {% load bootstrap4 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {#        {{ form.media.css }}#}
    {% load static %}


    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
    {% block extra_head %}
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Canterbury Trails</title>
    <meta name="author" content="FatherChill">
</head>
<body class="bg-light">

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary static-top">
    <div class="container mt-0 p-0">
        <a class="navbar-brand display-1" href={% url 'courses:index' %}><h3 class="mb-0">Canterbury Trails</h3></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="#">About</a>#}
{#                </li>#}
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href={% url 'courses:create' %}>Share Course</a>
                    {% else %}
                        <a href="#" data-toggle="modal" data-target="#loginModal" class="nav-link">Share Course</a>
                    {% endif %}

                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true" aria-expanded="false"><u><i>{{ user.username }}</i></u></a>
                    <div class="dropdown-menu dropdown-menu-right">
{#                    <a class="dropdown-item" href="{% url 'profiles:detail' slug=user.username %}">My Profile</a>#}
                    <a class="dropdown-item" href="{% url 'logout' %}?next={{request.path}}">Logout</a>
                    </div>
                </li>

                {% else %}
                    <a class="nav-link" href="{% url 'login' %}?next={{request.path}}">Login</a>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
        <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Login to contribute!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Consider joining our community, submitting your own courses, and helping others find the best
                        ones.
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <a class="btn btn-primary" href="{% url 'login'  %}?next={{request.path}}" role="button">Login</a>
                    </div>
                </div>
            </div>
        </div>
<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirm Deletion!</h5>
            </div>
            <div class="modal-body">
                Are you sure? This action cannot be undone.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <a class="btn btn-danger btn-ok">Delete</a>
            </div>
        </div>
    </div>
</div>


<!-- Page Content -->

{% block content %}
    if you see this something is terribly wrong
{% endblock content %}


<script>

    {% block extra_js %}
    {% endblock %}
</script>
</body>
</html>