CanterburyTales/courses/urls.py
from django.urls import path

from CanterburyTales.courses import views

app_name = 'courses'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    # ALL POSSIBLE INDEX URLS
    path('search/audience/<str:audience>/<int:audience_exact>/tags/<str:tags>/<int:tags_exact>/', views.IndexView.as_view(),
         name='index_full_search'),
    path('search/audience/<str:audience>/<int:audience_exact>/tags/<str:tags>/', views.IndexView.as_view(),
         name='index_search_1'),
    path('search/audience/<str:audience>/tags/<str:tags>/<int:tags_exact>/', views.IndexView.as_view(),
         name='index_full_search_2'),
    path('search/audience/<str:audience>/tags/<str:tags>/', views.IndexView.as_view(), name='index_full_search_3'),
    path('search/audience/<str:audience>/<int:audience_exact>/', views.IndexView.as_view(), name='index_audience_search'),
    path('search/audience/<str:audience>/', views.IndexView.as_view(), name='index_audience_search'),
    path('search/tags/<str:tags>/<int:tags_exact>/', views.IndexView.as_view(), name='index_tag_search'),
    path('search/tags/<str:tags>/', views.IndexView.as_view(), name='index_tag_search'),


    # handle other urls
    path('courses/create/', views.CourseCreate.as_view(), name='create'),
    path('courses/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('courses/<int:pk>/edit', views.CourseUpdate.as_view(), name='edit'),
    path('courses/upvote/<int:pk>/', views.course_upvote, name='upvote'),
    path('courses/addDownload/<int:pk>/', views.course_add_download, name='add_download'),
    path('courses/<int:pk>/delete/', views.course_delete, name='delete'),
    path('courses/<int:c_id>/newFile/', views.add_file, name='add_file'),
    path('courses/<int:c_id>/deleteFile/<int:f_id>/', views.delete_file, name='delete_file'),

]

CanterburyTales/profiles/urls.py
# profile/urls.py
from django.urls import path

from CanterburyTales.profiles import views

app_name = 'profiles'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('<slug:slug>/', views.DetailView.as_view(), name='detail')
]

CanterburyTales/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('django.contrib.auth.urls')),
    path('', include('CanterburyTales.courses.urls')),
    path('profiles/', include('CanterburyTales.profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CanterburyTales/courses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.models import User
from CanterburyTales.profiles.models import Profile
from django.contrib.postgres.fields import IntegerRangeField
from django.shortcuts import render, redirect

from django.urls import reverse
import os
import math
import datetime


class Tag(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.title


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/uploads/courses/username/datetime/<filename>
    user_n = instance.course.author.user.username
    course_title = ''.join(e for e in instance.course.title[:15] if e.isalnum())

    return os.path.join('courses', user_n, course_title, filename)


class Course(models.Model):
    title = models.CharField(max_length=100, blank=False)
    year_written = models.IntegerField(default=timezone.now().year)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    posted = models.DateField(null=True, )
    description = models.TextField()
    tags = models.ManyToManyField(Tag)
    audience = IntegerRangeField()
    count = models.IntegerField(default=1)
    duration = models.DurationField(null=True, default=30)
    upvotes = models.ManyToManyField(Profile, related_name='upvotes', blank=True)
    views = models.IntegerField(default=0)
    downloads = models.IntegerField(default=0)

    def get_absolute_url(self):
        return redirect('courses:detail', pk=self.pk)

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.title

    def audience_description(self):
        return Audience().get_description(self.audience.lower, self.audience.upper)

    def views_humanized(self):
        return humanized_count(self.views)

    def posted_humanized(self):
        return humanized_duration(datetime.date.today(), self.posted)

    def add_view(self):
        self.views = self.views + 1
        self.save()

    def add_download(self):
        self.views = self.views + 1
        self.save()

    def duration_long(self):
        minutes = self.duration_minutes()
        long = ''
        if minutes >= 60:
            long += str(int(minutes / 60)) + ' hrs'

        if minutes % 60 != 0:
            if long != '':
                long += ', '
            long += str(int(minutes % 60)) + ' min'

        return long

    def duration_minutes(self):
        sec = self.duration.seconds
        if sec < 60:
            return sec
        else:
            return int(self.duration.seconds / 60)



def humanized_count(i):
    if i <= 10:
        return str(i)
    elif i <= 200:
        return str(math.floor(i / 10) * 10) + '+'
    elif i <= 1000:
        return str(math.floor(i / 100) * 100) + '+'
    elif i <= 10000:
        return str(math.floor(i / 1000) * 1000) + '+'
    elif i <= 100000:
        return str(math.floor(i / 10000) * 10000) + '+'
    elif i <= 1000000:
        return str(math.floor(i / 100000) * 100000) + '+'
    elif i > 1000000:
        return str(math.floor(i / 1000000)) + ' million +'
    else:
        return str(i)


def humanized_duration(newer_date, older_date):
    days = (newer_date - older_date).days
    if days == 0:
        return 'Today'
    if days == 1:
        return 'Yesterday'
    if days < 30:
        return str(days) + ' days ago'
    elif days < 50:
        return '1 month'
    elif days < 365*2:
        return str(math.floor(days/(365/12))) + ' months ago'
    else:
        return  str(math.floor(days/365)) + ' years ago'


class CourseFile(models.Model):
    file = models.FileField(upload_to=user_directory_path)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def file_name(self):
        return self.file.file.name.split('/')[-1]


class Audience:
    def __init__(self):
        self.definitions = {
            0: 'Infant / Toddler',
            3: 'Pre-K',
            5: 'Kindergarten',
            6: '1st Grade',
            7: '2nd Grade',
            8: '3rd Grade',
            9: '4th Grade',
            10: '5th Grade',
            11: '6th Grade',
            12: '7th Grade',
            13: '8th Grade',
            14: '9th Grade',
            15: '10th Grade',
            16: '11th Grade',
            17: '12th Grade',
            18: 'University',
            22: 'Young Adults',
            50: 'Mid-life',
            65: 'Retired',
        }

        self.special = {
            "0,10": 'Children (Infant-5th Grade)',
            "11,13": 'Middle School',
            '14,17': 'High School',
            '11,17': 'Youth (Middle and High School)',
            '18,65': 'Adults (18-65)',
            '0,18': 'Children and Youth',
            '0,65': 'Everyone'
        }

    def get_title(self, age):
        return self.definitions.get(age)

    def get_range_titles(self, bounds):
        # if bounds is in special definitions, use that,
        # otherwise return text "5th Grade through 6th Grade"
        titles = (self.definitions.get(bounds[0]), self.definitions.get(bounds[1]))
        return titles

    def get_definitions(self):
        return self.definitions

    def get_definition(self, n):
        return self.definitions[n]

    def get_special_definitions(self):
        return self.special

    def get_special_definition(self, s):
        if s in self.special:
            return self.special[s]
        return False

    def get_description(self, lower, upper):
        description = self.get_special_definition(str(lower) + ',' + str(upper))
        if not description:
            description = self.get_definition(lower) + ' through ' + self.get_definition(upper)
        return description

CanterburyTales/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError


def content_file_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "avatar.%s" % ext
    return filename


def file_size(value): # add this to some file where you can import it from
    limit = 2 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 2 MiB.')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=True, null=True)
    org_name = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    about = models.TextField(null=True)
    pic = models.ImageField(null=True, blank=True,
                            upload_to='avatars/', validators=[file_size])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.user.username


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

CanterburyTales/courses/forms.py
from django import forms
from django_select2.forms import ModelSelect2TagWidget, Select2TagWidget, Select2MultipleWidget
from CanterburyTales.courses.models import Course, Tag, Profile, CourseFile
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class CourseForm(forms.ModelForm):
    # pseudo_tags = forms.MultipleChoiceField()

    class Meta:
        model = Course
        fields = [
            'title',
            'year_written',
            'tags',
            'audience',
            'count',
            'duration',
            'description',
        ]
        widgets = {
            # 'course_files': forms.FileInput(attrs={'multiple': True})
        }
        labels = {
            'duration': 'Lesson Duration',
            'count': 'Number of lessons',
            'tags': 'Tags'

        }

    course_files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    def __init__(self, *args, **kwargs):
        course = kwargs.pop('course', '')
        super(CourseForm, self).__init__(*args, **kwargs)
        self.base_fields['tags'] = forms.ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('title'),
                                                                  widget=TagsCustomWidget(
                                                                      attrs={"data-token-separators": '[","]'}))


class TagsCustomWidget(Select2TagWidget):
    queryset = Tag.objects.all()

    @property
    def empty_label(self):
        return 'Type in tags'

    def value_from_datadict(self, data, files, name):
        '''Create objects for given non-pimary-key values. Return list of all names as name is the to_field_name.'''
        values = set(super().value_from_datadict(data, files, name))
        # This may only work for Tag, if Tag has title field.
        # You need to implement this method yourself, to ensure proper object creation.
        ids = []
        for val in values:
            if val.isdigit():
                ids.append(val)
            else:
                ids.append(Tag.objects.create(title=val.title()).id)
        return ids


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['title', 'description']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'org_name',
            'city',
            'state',
            'title',
            'about',
            'pic'
        ]


class FilterForm(forms.Form):
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('title'),
                                          widget=Select2MultipleWidget)
    tags_exact = forms.BooleanField(label='Exact Match',
                                    help_text='Search will return courses with any selected tags (an "or" condition). '
                                              'Exact match will return courses containing all selected tags (an "and" '
                                              'condition).')
    audience_0 = forms.IntegerField()
    audience_1 = forms.IntegerField()
    audience_exact = forms.BooleanField(label='Strict Match',
                                        help_text='Search will return courses with an audience that falls within the '
                                              'selected range. Strict match will return courses with an exact audience '
                                              'match.')

CanterburyTales/profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from .models import Profile
from django.conf import settings
from django.core.exceptions import ValidationError


def file_size(value): # add this to some file where you can import it from
    limit = 2 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 2 MiB.')


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email',)

        labels = {
            'password': "Last 4 digits of a phone number. Or any other passcode or passphrase you like",
            'password2': "Same 4 digits",
            'email': "Email"

        }
        help_texts = {
            'password1': "Your phone? Your church's phone? We will never ask for any sensitive data. So don't stress about remembering a difficult password.",
            'password2': "In case you mistyped it the first time.",
            'email': "So you can receive email notifications or others can contact you."
        }


class ProfileForm(forms.ModelForm):
    org_name = forms.CharField(max_length=100, label='Your church or organization', help_text='Church/Org')
    title = forms.CharField(max_length=50, help_text="Are you a Sunday School teacher? Youth leader? Rector?",
                            label="What's your role?")
    city = forms.CharField(max_length=50, label='City',
                           help_text="So people know a little bit about where you are from.")
    state = forms.CharField(max_length=50, label='State', help_text='State')
    about = forms.CharField(
        max_length=1000,
        label='What else should we know about you?',
        help_text='I am passionate about...',
        widget=forms.Textarea
    )
    pic = forms.FileField(label='Profile Picture', help_text='Must be less than 2Mb')

    class Meta:
        model = Profile
        fields = ('org_name', 'title', 'city', 'state', 'about', 'pic')

CanterburyTales/profiles/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import SignUpForm, ProfileForm
from django.views import generic
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404


def signup(request):
    if request.method == 'POST':
        user_form = SignUpForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.refresh_from_db()
            profile_form = ProfileForm(request.POST, instance=user.profile)
            profile_form.full_clean()
            profile_form.save()
            username = user_form.cleaned_data.get('username')
            raw_password = user_form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('courses:index')
    else:
        user_form = SignUpForm()
        profile_form = ProfileForm()
    return render(request, 'profile/signup.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = User
    template_name = 'profile/detail.html'
    slug_field = 'username'
    login_url = 'login'

CanterburyTales/templates/courses/course_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load custom_tags %}
{% load static %}
{% block extra_head %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.6.2/css/bootstrap-slider.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'courses/bootstrap-duration-picker.css' %} " />
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.6.2/bootstrap-slider.min.js"></script>
          <script type="text/javascript" src="{% static "courses/script.js" %}"></script>
        <script type="text/javascript" src="{% static "courses/bootstrap-duration-picker.js" %}"></script>
    {{ form.media.css }}
    {{ form.media.js }}
{% endblock %}

{% block content %}
    <div class="container">
        <form role="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {#    {{ form.as_ul}}#}
                    {% bootstrap_form_errors form layout='' %}

            {% bootstrap_form_ form %}

            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    Submit
                </button>
            {% endbuttons %}
        </form>
    </div>
    <div id='audience_titles'><span id="audience_lower"></span> through <span id="audience_upper"></span></div>
    <div id='slider_container'>
        <div id='audience_slider'></div>
    </div>

{% endblock %}


{% block extra_js %}



    var $audience = {% autoescape off %}{% audience_map %}{% endautoescape %};
    var $audience_special = {% autoescape off %}{% audience_special_map %}{% endautoescape %};
    var $ages = {% audience_breakpoints %}

    $( document ).ready(function() {
        $('#id_duration').durationPicker({
    showSeconds: false,
    showDays: false,
});
    $('#id_duration').data('durationPicker').setValue(1800);

    $("#id_audience_0, #id_audience_1").hide();
    $("#audience_titles").appendTo( $("#id_audience_0").parent() );
    $("#slider_container").appendTo( $("#id_audience_0").parent() );
    var $a_slider = createAudienceSlider($('#audience_slider'), $ages, initial=[18,65], enabled=true);

    setElements([18,65]);

    $a_slider.on("slide", function (slideEvt) {
        setElements($('#audience_slider').val());
    });

    function setElements(value_array) {
        $("#audience_titles").text(getTitles(value_array, $audience_special, $audience));
        document.getElementById("id_audience_0").value = $('#audience_slider').val()[0];
        document.getElementById("id_audience_1").value = $('#audience_slider').val()[1];
    }
    });





{% endblock %}

CanterburyTales/templates/courses/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load custom_tags %}
{% load static %}
{% block extra_head %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.6.2/css/bootstrap-slider.min.css"/>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.6.2/bootstrap-slider.min.js"></script>
    <script type="text/javascript" src="{% static "courses/script.js" %}"></script>
    {{ form.media.css }}
    {{ form.media.js }}
{% endblock %}

{% block content %}
    <div class="container">
        {% if not user.is_authenticated %}
        <div class="row">
            <div class="col ">

                <div class="card bg-info text-white mt-5">
                    <div class="card-body">
                        <div class="row pl-3 pr-3">
                            <div class="col-md-4">
                                <div class="row">
                                    Canterbury Tales is a place for clergy and laity to share
                                    Anglican-flavored non-copyrighted lesson plans.
                                </div>
                                <div class="row mt-3 mb-3">
                                    <a class="btn btn-primary pl-4 pr-4" href="{% url 'login' %}" role="button">Join!</a>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <h6><b>How it works:</b></h6>
                                <div class="card-group">
                                    <div class="card bg-info border-info">
                                        <img src="{% static "courses/images/add.svg" %}" class="card-img-top" style="max-height: 50px"/>
                                        <div class="card-body">
                                            <p class="card-text small">We all share self-written lessons with the broader Anglican Church.</p>
                                        </div>
                                    </div>
                                    <div class="card bg-info border-info">
                                        <img src="{% static "courses/images/thumb_up.svg" %}" class="card-img-top" style="max-height: 50px"/>
                                        <div class="card-body">
                                            <p class="card-text small">Fellow teachers and clergy upvote the most useful courses.</p>
                                        </div>
                                    </div>
                                    <div class="card bg-info border-info">
                                        <img src="{% static "courses/images/trending_up.svg" %}" class="card-img-top" style="max-height: 50px"/>
                                        <div class="card-body">
                                            <p class="card-text small">The best lessons rise to the top.</p>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="row mt-5 justify-content-between">
            <div class="col-md-3 order-md-2 mb-4 " id="filter_column">
                <div class="accordion">
                    <form method="get" class="form">
                        {% csrf_token %}
                        <div class="card bg-white">
                            <div class="card-header" id="headingOne">
                                <h1 class="mb-0">
                                    <a class="btn btn-link" type="button" data-toggle="collapse"
                                       data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                        Filter Tags
                                    </a>
                                </h1>
                            </div>
                            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne"
                                 data-parent="#accordionExample">
                                <div class="card-body">
                                    {% bootstrap_field form.tags show_label=False %}
                                    {% bootstrap_field form.tags_exact %}
                                </div>
                            </div>
                        </div>
                        <div class="card bg-white">
                            <div class="card-header" id="headingtwo">
                                <h2 class="mb-0">
                                    <a class="btn btn-link" type="button" data-toggle="collapse"
                                       data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                                        Filter Audience
                                    </a>
                                </h2>
                            </div>
                            <div id="collapseTwo" class="collapse show" aria-labelledby="headingtwo"
                                 data-parent="#accordionExample">
                                <div class="card-body">
                                    {% bootstrap_field form.audience_0 show_label=False %}
                                    {% bootstrap_field form.audience_1 show_label=False %}
                                    {% bootstrap_field form.audience_exact show_label=False %}
                                    <div id='audience_titles'><span id="audience_lower"></span> through <span
                                            id="audience_upper"></span></div>
                                    <div id='slider_container'>
                                        <div id='audience_filter'></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-9 order-md-1">
                <div class="bg-white border rounded-top pt-2 px-4 text-center" style="border: 1px solid rgba(0,0,0,.125);">
                    <h1 class=" ">New and Popular Courses</h1>
                </div>
                {% if courses %}
                    {% include "courses/course_list.html" %}
                {% else %}
                    <p>No courses are available</p>
                {% endif %}


            </div>
        </div>
    </div>

{% endblock %}

{% block extra_js %}
    var $audience = {% autoescape off %}{% audience_map %}{% endautoescape %};
    var $audience_special = {% autoescape off %}{% audience_special_map %}{% endautoescape %};
    var $ages = {% audience_breakpoints %}
    var $initial_values = [parseInt($("#id_audience_0").val()),parseInt($("#id_audience_1").val())];


    $(document).ready(function () {
    $("#id_audience_0, #id_audience_1").hide();
    $("#audience_titles").appendTo($("#id_audience_0").parent());
    $("#slider_container").appendTo($("#id_audience_0").parent());
    let $a_slider = createAudienceSlider($('#audience_filter'), $ages, initial = $initial_values, enabled = true);

    setElements($initial_values);

    $a_slider.on("slide", function (slideEvt) {
    setElements($('#audience_filter').val());
    });

    function setElements(value_array) {
    $("#audience_titles").text(getTitles(value_array, $audience_special, $audience));
    document.getElementById("id_audience_0").value = $('#audience_filter').val()[0];
    document.getElementById("id_audience_1").value = $('#audience_filter').val()[1];
    }

    $('#id_audience_0, #id_audience_1, #id_audience_exact, #id_tags, #id_tags_exact').change(function(){
    trigger_courses_call();
    });

    $a_slider.on("slideStop", function (slideEvt) {
    trigger_courses_call();
    });

    $(".audience_slider").each(function (index) {
    $(this).bootstrapSlider({
    range: true,
    min: 0,
    max: 65,
    lock_to_ticks: true,
    id: index,
    value: $(this).data('slider'),
    enabled: false,
    });
    });

    });

    function trigger_courses_call(){
    var $response = get_courses($('#id_audience_0').val(), $('#id_audience_1').val(),
    $('#id_audience_exact').is(":checked") ? 1 : 0, $('#id_tags').val().join('&') || 'all',
    $('#id_tags_exact').is(":checked") ? 1 : 0);
    }

    // AJAX for posting
    function get_courses(a_low, a_high, a_match, tags, tags_match){

    $.ajax({
    url : "search/audience/" + a_low + '-' + a_high + '/' + a_match + '/tags/' + tags + '/' + tags_match,
    type : "GET", // http method
    dataType: "html", // data sent with the post request

    // handle a successful response
    success : function(json) {
    $('#courses').replaceWith(json); // remove the value from the input
    $(".audience_slider").each(function (index) {
    $(this).bootstrapSlider({
    range: true,
    min: 0,
    max: 65,
    lock_to_ticks: true,
    id: index,
    value: $(this).data('slider'),
    enabled: false,
    });
    });

    },

    // handle a non-successful response
    error : function(xhr,errmsg,err) {
    $('#courses').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
        " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
    console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
    }
    });
    }
{% endblock %}