CanterburyTales/courses/urls.py
from django.urls import path

from CanterburyTales.courses import views

app_name = 'courses'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    # ALL POSSIBLE INDEX URLS
    path('search/audience/<str:audience>/<int:audience_exact>/tags/<str:tags>/<int:tags_exact>/', views.IndexView.as_view(),
         name='index_full_search'),
    path('search/audience/<str:audience>/<int:audience_exact>/tags/<str:tags>/', views.IndexView.as_view(),
         name='index_search_1'),
    path('search/audience/<str:audience>/tags/<str:tags>/<int:tags_exact>/', views.IndexView.as_view(),
         name='index_full_search_2'),
    path('search/audience/<str:audience>/tags/<str:tags>/', views.IndexView.as_view(), name='index_full_search_3'),
    path('search/audience/<str:audience>/<int:audience_exact>/', views.IndexView.as_view(), name='index_audience_search'),
    path('search/audience/<str:audience>/', views.IndexView.as_view(), name='index_audience_search'),
    path('search/tags/<str:tags>/<int:tags_exact>/', views.IndexView.as_view(), name='index_tag_search'),
    path('search/tags/<str:tags>/', views.IndexView.as_view(), name='index_tag_search'),


    # handle other urls
    path('courses/create/', views.CourseCreate.as_view(), name='create'),
    path('courses/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('courses/<int:pk>/edit', views.CourseUpdate.as_view(), name='edit'),
    path('courses/upvote/<int:pk>/', views.course_upvote, name='upvote'),
    path('courses/addDownload/<int:pk>/', views.course_add_download, name='add_download'),
    path('courses/<int:pk>/delete/', views.course_delete, name='delete'),
    path('courses/<int:c_id>/newFile/', views.add_file, name='add_file'),
    path('courses/<int:c_id>/deleteFile/<int:f_id>/', views.delete_file, name='delete_file'),

]

CanterburyTales/profiles/urls.py
# profile/urls.py
from django.urls import path

from CanterburyTales.profiles import views

app_name = 'profiles'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('<slug:slug>/', views.DetailView.as_view(), name='detail')
]

CanterburyTales/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('django.contrib.auth.urls')),
    path('', include('CanterburyTales.courses.urls')),
    path('profiles/', include('CanterburyTales.profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CanterburyTales/courses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.models import User
from CanterburyTales.profiles.models import Profile
from django.contrib.postgres.fields import IntegerRangeField
from django.shortcuts import render, redirect

from django.urls import reverse
import os
import math
import datetime


class Tag(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.title


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/uploads/courses/username/datetime/<filename>
    user_n = instance.course.author.user.username
    course_title = ''.join(e for e in instance.course.title[:15] if e.isalnum())

    return os.path.join('courses', user_n, course_title, filename)


class Course(models.Model):
    title = models.CharField(max_length=100, blank=False)
    year_written = models.IntegerField(default=timezone.now().year)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    posted = models.DateField(null=True, )
    description = models.TextField()
    tags = models.ManyToManyField(Tag)
    audience = IntegerRangeField()
    count = models.IntegerField(default=1)
    duration = models.DurationField(null=True, default=30)
    upvotes = models.ManyToManyField(Profile, related_name='upvotes', blank=True)
    views = models.IntegerField(default=0)
    downloads = models.IntegerField(default=0)

    def get_absolute_url(self):
        return redirect('courses:detail', pk=self.pk)

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.title

    def audience_description(self):
        return Audience().get_description(self.audience.lower, self.audience.upper)

    def views_humanized(self):
        return humanized_count(self.views)

    def posted_humanized(self):
        return humanized_duration(datetime.date.today(), self.posted)

    def add_view(self):
        self.views = self.views + 1
        self.save()

    def add_download(self):
        self.views = self.views + 1
        self.save()

    def duration_long(self):
        minutes = self.duration_minutes()
        long = ''
        if minutes >= 60:
            long += str(int(minutes / 60)) + ' hrs'

        if minutes % 60 != 0:
            if long != '':
                long += ', '
            long += str(int(minutes % 60)) + ' min'

        return long

    def duration_minutes(self):
        sec = self.duration.seconds
        if sec < 60:
            return sec
        else:
            return int(self.duration.seconds / 60)



def humanized_count(i):
    if i <= 10:
        return str(i)
    elif i <= 200:
        return str(math.floor(i / 10) * 10) + '+'
    elif i <= 1000:
        return str(math.floor(i / 100) * 100) + '+'
    elif i <= 10000:
        return str(math.floor(i / 1000) * 1000) + '+'
    elif i <= 100000:
        return str(math.floor(i / 10000) * 10000) + '+'
    elif i <= 1000000:
        return str(math.floor(i / 100000) * 100000) + '+'
    elif i > 1000000:
        return str(math.floor(i / 1000000)) + ' million +'
    else:
        return str(i)


def humanized_duration(newer_date, older_date):
    days = (newer_date - older_date).days
    if days == 0:
        return 'Today'
    if days == 1:
        return 'Yesterday'
    if days < 30:
        return str(days) + ' days ago'
    elif days < 50:
        return '1 month'
    elif days < 365*2:
        return str(math.floor(days/(365/12))) + ' months ago'
    else:
        return  str(math.floor(days/365)) + ' years ago'


class CourseFile(models.Model):
    file = models.FileField(upload_to=user_directory_path)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def file_name(self):
        return self.file.file.name.split('/')[-1]


class Audience:
    def __init__(self):
        self.definitions = {
            0: 'Infant / Toddler',
            3: 'Pre-K',
            5: 'Kindergarten',
            6: '1st Grade',
            7: '2nd Grade',
            8: '3rd Grade',
            9: '4th Grade',
            10: '5th Grade',
            11: '6th Grade',
            12: '7th Grade',
            13: '8th Grade',
            14: '9th Grade',
            15: '10th Grade',
            16: '11th Grade',
            17: '12th Grade',
            18: 'University',
            22: 'Young Adults',
            50: 'Mid-life',
            65: 'Retired',
        }

        self.special = {
            "0,10": 'Children (Infant-5th Grade)',
            "11,13": 'Middle School',
            '14,17': 'High School',
            '11,17': 'Youth (Middle and High School)',
            '18,65': 'Adults (18-65)',
            '0,18': 'Children and Youth',
            '0,65': 'Everyone'
        }

    def get_title(self, age):
        return self.definitions.get(age)

    def get_range_titles(self, bounds):
        # if bounds is in special definitions, use that,
        # otherwise return text "5th Grade through 6th Grade"
        titles = (self.definitions.get(bounds[0]), self.definitions.get(bounds[1]))
        return titles

    def get_definitions(self):
        return self.definitions

    def get_definition(self, n):
        return self.definitions[n]

    def get_special_definitions(self):
        return self.special

    def get_special_definition(self, s):
        if s in self.special:
            return self.special[s]
        return False

    def get_description(self, lower, upper):
        description = self.get_special_definition(str(lower) + ',' + str(upper))
        if not description:
            description = self.get_definition(lower) + ' through ' + self.get_definition(upper)
        return description

CanterburyTales/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError


def content_file_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "avatar.%s" % ext
    return filename


def file_size(value): # add this to some file where you can import it from
    limit = 2 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 2 MiB.')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=True, null=True)
    org_name = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    about = models.TextField(null=True)
    pic = models.ImageField(null=True, blank=True,
                            upload_to='avatars/', validators=[file_size])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.user.username


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

CanterburyTales/courses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from django import forms
from .forms import CourseForm, FilterForm
import datetime
from .models import Course, Profile, User, Tag, CourseFile, Audience
import zipfile
import os
from django.db.models import Count
from psycopg2.extras import Range, NumericRange
from django.contrib.postgres.fields import IntegerRangeField
from django.db import models
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect


class IndexView(generic.TemplateView):
    # template_name = 'courses/index.html'

    def get_template_names(self):
        if self.request.is_ajax():
            return 'courses/course_list.html'
        return 'courses/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_params'] = {
            'audience': parse_audience_params(self.kwargs.get('audience', '0,65')),
            'audience_exact': bool(self.kwargs.get('audience_exact', 0)),
            'tags': parse_tag_params(self.kwargs.get('tags', '')),
            'tags_exact': bool(self.kwargs.get('tags_exact', 0)),
        }
        context['courses'] = self.get_queryset(context['search_params'])
        context['form'] = FilterForm(initial={
            'audience_0': context['search_params']['audience'][0],
            'audience_1': context['search_params']['audience'][1],
            'audience_exact': context['search_params']['audience_exact'],
            'tags': context['search_params']['tags'],
            'tags_exact': context['search_params']['tags_exact'],
        }
        )
        return context

    def get_queryset(self, params):
        queryset = filter_audience(params['audience'], params['audience_exact'])
        queryset = filter_tags(queryset, params['tags'], params['tags_exact'])

        queryset = queryset.annotate(num_upvotes=Count('upvotes')) \
            .order_by('-num_upvotes', '-views')
        return queryset


class DetailView(generic.DetailView):
    model = Course
    template_name = 'courses/detail.html'
    fields = [
        'title',
        'year_written',
        'tags',
        'audience',
        'lesson_length',
        'description',
    ]

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        obj = self.get_object()
        obj.add_view()
        return context


class CourseCreate(LoginRequiredMixin, FormView):
    template_name = 'courses/course_form.html'
    form_class = CourseForm
    success_url = '/'
    login_url = 'login'

    def form_valid(self, form):
        course = form.save(commit=False)
        course.author = Profile.objects.all().first()
        course.posted = datetime.date.today()
        course.save()
        form.save_m2m()
        for f in form.files.getlist('course_files'):
            CourseFile.objects.create(file=f, course=course)

        return super().form_valid(form)


class CourseUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'courses/course_form.html'
    form_class = CourseForm
    model = Course
    login_url = 'login'


def course_delete(request, pk):
    course = Course.objects.get(pk=pk)
    if request.user == course.author.user:
        course.delete()
    return redirect("courses:index")


def course_upvote(request, pk):
    course = Course.objects.get(pk=pk)
    profile = request.user.profile
    course.upvotes.add(request.user.profile)
    course.save()
    return redirect('courses:index')


def course_add_download(request, pk):
    a = 1


def add_file(request, c_id):
    course = Course.objects.get(pk=c_id)
    if course.author.user == request.user:
        for file in request.FILES.getlist('course_files'):
            CourseFile.objects.create(file=file, course=course)
    return redirect('courses:detail', c_id)


def delete_file(request, course, file):
    file = CourseFile.objects.get(pk=file)
    if course == file.course.id:
        file.delete()
    return redirect('courses:detail', course)


def parse_audience_params(string):
    audience_defs = Audience().get_definitions().keys()
    a_range = string.split('-')

    if not len(a_range) == 2:
        return [0, 65]
    elif not (a_range[0].isdigit() & a_range[1].isdigit()):
        return [0, 65]
    else:
        temp_list = []
        for i in a_range:
            val = int(i)
            if val not in audience_defs:
                temp_i = 0
                for age in audience_defs:
                    if age <= val:
                        temp_i = age
                    else:
                        break
                temp_list.append(temp_i)
            else:
                temp_list.append(val)
        a_range = temp_list
    return a_range


def filter_audience(audience, match_type):
    if match_type:
        return Course.objects.filter(audience__startswith=audience[0]).filter(audience__endswith=audience[1])
    else:
        return Course.objects.filter(audience__overlap=NumericRange(audience[0], audience[1]))


def parse_tag_params(string):
    tags = []
    if string == '' or string == 'all':
        return ''

    for tag in string.split('&'):
        if tag.isdigit():
            tags.append(tag)
            tags_set = Tag.objects.filter(id__in=tags)
        else:
            tags.append(tag.title())
            tags_set = Tag.objects.filter(title__in=tags)

    return tags_set.values_list('id', flat=True)


def filter_tags(queryset, tags, match_type):
    if tags == '':
        return queryset
    if match_type:
        for tag in tags:
            queryset = queryset.filter(tags=tag)
        return queryset
    else:
        return queryset.filter(tags__in=tags)

CanterburyTales/profiles/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import SignUpForm, ProfileForm
from django.views import generic
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404


def signup(request):
    if request.method == 'POST':
        user_form = SignUpForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.refresh_from_db()
            profile_form = ProfileForm(request.POST, instance=user.profile)
            profile_form.full_clean()
            profile_form.save()
            username = user_form.cleaned_data.get('username')
            raw_password = user_form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('courses:index')
    else:
        user_form = SignUpForm()
        profile_form = ProfileForm()
    return render(request, 'profile/signup.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = User
    template_name = 'profile/detail.html'
    slug_field = 'username'
    login_url = 'login'

CanterburyTales/templates/profile/detail.html
<!-- templates/profile/signup.html -->
{% extends 'base.html' %}
{% load bootstrap4 %}
{{ form.media.css }}

{% block content %}
    <div class="container">
        {% if user.is_authenticated %}
            <h1>{{ user }}</h1>
        {% else %}
            <h1>Not Logged in</h1>
        {% endif %}
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <div class="row">
                            <div class="col-sm-auto">
                                {% if user.profile.pic %}
                                    <img class="rounded-circle avatar avatar-original" style="-webkit-user-select:none;
              display:block; margin:auto; width:200px; max-height: 200px" src={{ user.profile.pic.url }}>
                                {% endif %}
                            </div>
                            <div class="col-md">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md">
                                            <h1 class="mb-0">{{ user.username }}</h1>
                                        </div>
                                        <div class="col-sm-auto">
                                            <div class="d-inline align-middle">
                                                <button class="btn btn-default">
                                                    <div class="align-middle"><i class="material-icons medium">edit</i>&nbsp;Edit
                                                    </div>
                                                </button>

                                                <div class="float-right pl-3">
                                                    <i class="material-icons text-info">comment</i>&nbsp;500
                                                </div>
                                                <div class="float-right pl-3">
                                                    <i class="material-icons text-success">thumb_up</i>&nbsp;1500
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <h5 class="font-italic mb-0">{{ user.profile.title }}</h5>
                                    <p>{{ user.profile.org_name }}, {{ user.profile.city }}, {{ user.profile.state }}</p>
                                    <p>{{ user.profile.about }}</p>
                                </div>


                            </div>
                        </div>

                        <div class="row">
                <div class="row bg-white border rounded-top" style="border: 1px solid rgba(0,0,0,.125);">
                                <h1>Courses:</h1>
                            {% with courses=user.profile.course_set.all %}

                                {% if courses %}
                                    {% include "courses/course_list.html" %}
                                {% else %}
                                    <p>No courses are available</p>
                                {% endif %}
                            {% endwith %}
                            </div>
                            <div class="col-sm-auto m-3 bg-info border-dark border-primary rounded hidden d-none">
                                <div class="row"></div>
                                <h2>Recent Likes</h2>
                                <div class="row"></div>
                                <h2>Recent Comments</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

CanterburyTales/templates/profile/my_profile.html
<!-- templates/profile/signup.html -->
{% extends 'base.html' %}
{% load bootstrap4 %}
{{ form.media.css }}


{% block content %}
    <div class="container">
        <br>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-body">

                            <div class="row">
                                <div class="col-sm-auto">
                                    <img class="rounded-circle avatar avatar-original" style="-webkit-user-select:none;
              display:block; margin:auto; width:200px; max-height: 200px" src={{ user.profile.pic.url }}>
                                </div>
                                <div class="col-md">
                                        <div class="col-md-12">
                                            <div class="row">
                                                <div class="col-md">
                                                    <h1 class="mb-0">{{ user.username }}</h1>
                                                </div>
                                                <div class="col-sm-auto">
                                                    <div class="d-inline align-middle">
                                                    <button class="btn btn-default"><div class="align-middle"><i class="material-icons medium">edit</i>&nbsp;Edit</div> </button>

                                                    <div class="float-right pl-3">
                                                        <i class="material-icons text-info">comment</i>&nbsp;500
                                                    </div>
                                                    <div class="float-right pl-3">
                                                        <i class="material-icons text-success">thumb_up</i>&nbsp;1500
                                                    </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <h5 class="font-italic mb-0">{{ user.profile.title }}</h5>
                                            <p>{{ user.profile.org_name }}, {{ user.profile.city }}, {{ user.profile.state }}</p>
                                            <p>{{ user.profile.about }}</p>
                                        </div>


                                </div>
                            </div>

                            <div class="row border border-primary rounded-bottom">
                                <div class="col-lg m-3 bg-light border border-secondary rounded">
                                    <h1>Courses:</h1>
                                </div>
                                <div class="col-sm-auto m-3 bg-info border-dark border-primary rounded">
                                    <div class="row"></div><h2>Recent Likes</h2>
                                    <div class="row"></div><h2>Recent Comments</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

CanterburyTales/templates/profile/signup.html
<!-- templates/profile/signup.html -->
{% extends 'base.html' %}
{% load bootstrap4 %}
{{ form.media.css }}


{% block content %}
    <div class="container">
        <h2>Signup</h2>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form_errors user_form layout='inline' %}
            {% bootstrap_form_errors profile_form layout='inline' %}

            {% bootstrap_form user_form layout='inline' %}
            {#            {% bootstrap_form profile_form layout='inline' %}#}

            {% bootstrap_field profile_form.org_name layout='inline' %}

            {% bootstrap_field profile_form.title layout='inline' %}

            {% bootstrap_field profile_form.city layout='inline' %}
            {% bootstrap_field profile_form.state layout='inline' %}


            {% bootstrap_field profile_form.about layout='inline' %}
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="id_pic">
                <label class="custom-file-label text-muted" for="id_pic">Profile Picture</label>
                <small class="form-text text-muted">Must be less than 2Mb</small>
            </div>
            <button type="submit" class="btn btn-primary mt-3">Sign up</button>

        </form>
    </div>

{% endblock %}